import * as React from "react";
import Head from "next/head";

export default function Home() {
  const [theme, setTheme] = React.useState("light");

  function toggleDarkmode() {
    setTheme((p) => (p === "light" ? "dark" : "light"));
    document.documentElement.classList.toggle("dark");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center h-full flex-col">
        <h1 className="text-6xl font-semibold mb-5">
          Current Theme: <span className="text-sky-500">{theme}</span>
        </h1>

        <p className="my-5">
          When using <Highlight>@apply</Highlight> in a css file, it will not apply the{" "}
          <Highlight>dark:</Highlight> variants. However the button styles will update since it is
          using <Highlight>className</Highlight>
        </p>

        <button
          className=" bg-gray-300 text-neutral-900 dark:bg-neutral-900 dark:text-white px-5 py-3 rounded-md hover:bg-gray-400 dark:hover:bg-neutral-800 transition-colors"
          onClick={toggleDarkmode}
        >
          Toggle Darkmode
        </button>
      </main>
    </>
  );
}

function Highlight({ children }) {
  return <code className="font-mono bg-gray-100 px-1 p-0.5 rounded-sm">{children}</code>;
}
